[dev]

HOST_ZJGYY = '10.119.6.93'
PORT_ZJGYY = 3306
USER_ZJGYY = 'power'
PWD_ZJGYY =  '789-357*tgb'
SSH_HOST_ZJGYY = '10.118.1.79'
SSH_PWD_ZJGYY = 'TjsGyszBntg-1031'
SSH_USER_ZJGYY = 'root'

HOST_ZJLS = '10.119.3.144'
PORT_ZJLS = 3306
USER_ZJLS = 'power'    
PWD_ZJLS = '789-357*tgb'
SSH_HOST_ZJLS = '10.118.1.79'
SSH_PWD_ZJLS = 'TjsGyszBntg-1031'
SSH_USER_ZJLS = 'root'

HOST_SA = 'sadb.idc.sjtu.edu.cn'
PORT_SA = 13136
USER_SA = 'sams'        
PWD_SA = 'sakyglztSJK114'
SSH_HOST_SA = '10.118.1.79'
SSH_PWD_SA = 'TjsGyszBntg-1031'
SSH_USER_SA = 'root'

HOST_RSC = 'db-rsc.idc.sjtu.edu.cn'
PORT_RSC = 1443
USER_RSC = 'user_kfrssb'
PWD_RSC = 'Renshishebei42'
SSH_HOST_RSC = '10.118.1.192'
SSH_PWD_RSC = 'zjycy20dnl-025F'
SSH_USER_RSC = 'root'


HOST_GXK = '10.120.64.12'
PORT_GXK = 1521
USER_GXK = 'sharedb'
PWD_GXK = 'sjtu_nor'
SERVICE_NAME = 'coredb'
SSH_HOST_GXK = '10.118.1.79'
SSH_PWD_GXK = 'TjsGyszBntg-1031'
SSH_USER_GXK = 'root'






HOST_LOCAL = 'localhost'
PORT_LOCAL = 3306
USER_LOCAL = 'root'
PWD_LOCAL = '131438Hugo'


         